# Docker compose configuration for development

x-common-spec: &common-spec
  env_file: .env


services:
  node:
    <<: *common-spec
    build:
      context: .
      dockerfile: Dockerfile-node
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - "./app:/app"
      - ".data/node_modules:/app/node_modules"
      - ".data/yarn:/usr/local/share/.cache/yarn"
      - "./app/outstatic/content:/app/outstatic/content"
    command:
      - "yarn && yarn dev"
